version: '3'

services:
  web:
    build: ./pbs/
    restart: on-failure
    volumes:
      - ./pbs/:/code
    command: bash -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8999:8000"
