# Generated by Django 4.0.3 on 2022-04-07 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('img', models.URLField(blank=True, null=True, verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('img', models.URLField(blank=True, null=True, verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('img', models.URLField(blank=True, null=True, verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('discord', models.CharField(blank=True, max_length=100, null=True, verbose_name='Discord')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('friends', models.ManyToManyField(blank=True, null=True, to='core.user', verbose_name='Друзья')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='core.user', verbose_name='Игрок')),
            ],
        ),
        migrations.CreateModel(
            name='UserGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achives', models.ManyToManyField(blank=True, null=True, related_name='usergames', to='core.achive', verbose_name='Достижения')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usergames', to='core.game', verbose_name='Игра')),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergames', to='core.guild', verbose_name='Гильдия')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.usergames', verbose_name='Игрок'),
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Адрес')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('img', models.URLField(blank=True, null=True, verbose_name='Изображение')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('usergames', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='core.usergames', verbose_name='Игра пользователя')),
            ],
        ),
    ]
