# Generated by Django 4.0.3 on 2022-04-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='core.user', verbose_name='Друзья'),
        ),
        migrations.AlterField(
            model_name='usergames',
            name='achives',
            field=models.ManyToManyField(related_name='usergames', to='core.achive', verbose_name='Достижения'),
        ),
    ]
