# Generated by Django 4.0.3 on 2022-04-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_friends_alter_usergames_achives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AlterField(
            model_name='user',
            name='games',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.usergames', verbose_name='Игрок'),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_friends', to='core.user', verbose_name='Друг')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiends', to='core.user', verbose_name='Владелец')),
            ],
        ),
    ]
