# Generated by Django 4.0.3 on 2022-04-07 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_friend_friend_alter_friend_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='owner',
        ),
        migrations.AddField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='core.user', verbose_name='Игрок'),
            preserve_default=False,
        ),
    ]
