# Generated by Django 4.0.3 on 2022-04-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_games_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Размещено предложение'), (1, 'Ожидание подтверждения'), (2, 'Сделка завершена')], verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_author', to='core.user', verbose_name='Автор')),
                ('needed_items', models.ManyToManyField(to='core.nft', verbose_name='Список для обмена')),
                ('offered_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_item', to='core.nft', verbose_name='Предлагаемый предмет')),
            ],
        ),
        migrations.CreateModel(
            name='WikiArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_author', to='core.user', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='OfferResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_reponse_author', to='core.user', verbose_name='Автор отклика')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_reponses', to='core.offer', verbose_name='Предложение')),
                ('offered_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_reponses_item', to='core.nft', verbose_name='Предлагаемый предмет')),
            ],
        ),
    ]
