# Generated by Django 4.0.3 on 2022-04-17 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_offer_wikiarticle_offerresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerresponse',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
