ABI = [
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "internalType": "address", "name": "token", "type": "address"}],
        "name": "ERC1155ForLendRemoved",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "internalType": "address", "name": "token", "type": "address"}],
        "name": "ERC1155ForLendUpdated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "internalType": "address", "name": "token", "type": "address"}],
        "name": "ERC721ForLendRemoved",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [{"indexed": False, "internalType": "address", "name": "token", "type": "address"}],
        "name": "ERC721ForLendUpdated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "previousOwner", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "newOwner", "type": "address"},
        ],
        "name": "OwnershipTransferred",
        "type": "event",
    },
    {"anonymous": False, "inputs": [], "name": "Received", "type": "event"},
    {
        "inputs": [
            {"internalType": "address", "name": "", "type": "address"},
            {"internalType": "uint256", "name": "", "type": "uint256"},
        ],
        "name": "UsersLend",
        "outputs": [
            {"internalType": "uint256", "name": "status", "type": "uint256"},
            {"internalType": "address", "name": "token", "type": "address"},
            {"internalType": "uint256", "name": "tokenId", "type": "uint256"},
            {"internalType": "uint256", "name": "tokenStandard", "type": "uint256"},
            {"internalType": "address", "name": "borrower", "type": "address"},
            {"internalType": "address", "name": "fulfilledToken", "type": "address"},
            {"internalType": "uint256", "name": "fulfilledTokenId", "type": "uint256"},
            {"internalType": "uint256", "name": "fulfilledTokenStandard", "type": "uint256"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "", "type": "address"}],
        "name": "UsersLendCount",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "token", "type": "address"},
            {"internalType": "uint256", "name": "tokenId", "type": "uint256"},
            {"internalType": "uint256", "name": "tokenStandard", "type": "uint256"},
        ],
        "name": "approveBarter",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "token", "type": "address"},
            {"internalType": "uint256", "name": "tokenId", "type": "uint256"},
            {"internalType": "uint256", "name": "tokenStandard", "type": "uint256"},
            {"internalType": "address", "name": "borrower", "type": "address"},
        ],
        "name": "approveIterChainBarter",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "user", "type": "address"},
            {"internalType": "uint256", "name": "counter", "type": "uint256"},
        ],
        "name": "getAcceptedAddressesLend",
        "outputs": [{"internalType": "address[]", "name": "", "type": "address[]"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "user", "type": "address"},
            {"internalType": "uint256", "name": "counter", "type": "uint256"},
        ],
        "name": "getAcceptedIdsLend",
        "outputs": [{"internalType": "uint256[]", "name": "", "type": "uint256[]"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "user", "type": "address"},
            {"internalType": "uint256", "name": "counter", "type": "uint256"},
        ],
        "name": "getAcceptedStandardsLend",
        "outputs": [{"internalType": "uint256[]", "name": "", "type": "uint256[]"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "borrowedAtTimestamp", "type": "uint256"},
            {"internalType": "uint256", "name": "durationHours", "type": "uint256"},
        ],
        "name": "isDurationExpired",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "wantedToken", "type": "address"},
            {"internalType": "uint256", "name": "wantedTokenId", "type": "uint256"},
            {"internalType": "address", "name": "offerToken", "type": "address"},
            {"internalType": "uint256", "name": "offerTokenId", "type": "uint256"},
            {"internalType": "uint256", "name": "wantedTokenStandard", "type": "uint256"},
            {"internalType": "uint256", "name": "offerTokenStandard", "type": "uint256"},
        ],
        "name": "makeOffer",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "", "type": "address"},
            {"internalType": "address", "name": "", "type": "address"},
            {"internalType": "uint256[]", "name": "", "type": "uint256[]"},
            {"internalType": "uint256[]", "name": "", "type": "uint256[]"},
            {"internalType": "bytes", "name": "", "type": "bytes"},
        ],
        "name": "onERC1155BatchReceived",
        "outputs": [{"internalType": "bytes4", "name": "", "type": "bytes4"}],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "", "type": "address"},
            {"internalType": "address", "name": "", "type": "address"},
            {"internalType": "uint256", "name": "", "type": "uint256"},
            {"internalType": "uint256", "name": "", "type": "uint256"},
            {"internalType": "bytes", "name": "", "type": "bytes"},
        ],
        "name": "onERC1155Received",
        "outputs": [{"internalType": "bytes4", "name": "", "type": "bytes4"}],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "_operator", "type": "address"},
            {"internalType": "address", "name": "_from", "type": "address"},
            {"internalType": "uint256", "name": "_tokenId", "type": "uint256"},
            {"internalType": "bytes", "name": "_data", "type": "bytes"},
        ],
        "name": "onERC721Received",
        "outputs": [{"internalType": "bytes4", "name": "", "type": "bytes4"}],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "owner",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {"inputs": [], "name": "renounceOwnership", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
    {
        "inputs": [
            {"internalType": "address", "name": "token", "type": "address"},
            {"internalType": "uint256", "name": "tokenId", "type": "uint256"},
            {"internalType": "uint256", "name": "tokenStandard", "type": "uint256"},
        ],
        "name": "revokeBarter",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "token", "type": "address"},
            {"internalType": "uint256", "name": "tokenId", "type": "uint256"},
            {"internalType": "uint256", "name": "tokenStandard", "type": "uint256"},
            {"internalType": "address", "name": "borrower", "type": "address"},
        ],
        "name": "revokeIterChainBarter",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "token", "type": "address"},
            {"internalType": "uint256", "name": "tokenId", "type": "uint256"},
            {"internalType": "uint256", "name": "durationHours", "type": "uint256"},
            {"internalType": "address[]", "name": "acceptedToken", "type": "address[]"},
            {"internalType": "uint256[]", "name": "acceptedTokenId", "type": "uint256[]"},
            {"internalType": "uint256", "name": "tokenStandard", "type": "uint256"},
            {"internalType": "uint256[]", "name": "acceptedTokenStandard", "type": "uint256[]"},
        ],
        "name": "startBartering",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes4", "name": "interfaceId", "type": "bytes4"}],
        "name": "supportsInterface",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "newOwner", "type": "address"}],
        "name": "transferOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
]
